apiVersion: v1
kind: ConfigMap
metadata:
 name: config-autoscaler
 namespace: serving
data:
 enable-scale-to-zero: "false"
 scale-to-zero-grace-period: "30s"
 scale-to-zero-pod-retention-period: "0s"
 container-concurrency-target-default: "100"
 container-concurrency-target-percentage: "0.7"
 max-scale-up-rate: "1000"
 max-scale-down-rate: "2"
 panic-window-percentage: "10"
 panic-threshold-percentage: "200"
 stable-window: "60s"
 target-burst-capacity: "200"
 requests-per-second-target-default: "200"
