apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: serving-app 
  namespace: default 
spec:
  template:
    spec:
      containers:
        - image: santhu1039/myapp:0.6
  traffic:
    - revisionName: serving-app-00001
      percent: 100
